# site settings
title: Contend
subtitle: News & Updates
email: youremailaddress@gmail.com
description: Keep up to date with all of our latest news and teachings.
url: "" # the base hostname & protocol for your site

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6


# social settings
500px_url:
facebook_url: https://www.facebook.com/contend.church
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

collections:
  authors:
    title: Authors
    output: true

sass:
  style: compressed
